### ISSUE TITLE
`Incorrect header` when executed

### ISSUE THREAD

**Issue by khimaros** [egormanga/pinephone-fingerprint#3]
the i2c device is returning an unexpected header when called:

```
# ./pia.py 
< 55 aa 00 7f 00 00 00 00 da 2e
> 00 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
Traceback (most recent call last):
  File "/home/mobian/src/pinephone-fingerprint/./pia.py", line 74, in <module>
    if (__name__ == '__main__'): exit(main())
  File "/home/mobian/src/pinephone-fingerprint/./pia.py", line 72, in main
    print(fp.get_firmware_version())
  File "/home/mobian/src/pinephone-fingerprint/./pia.py", line 65, in get_firmware_version
    result, data = self.call(0x7F)
  File "/home/mobian/src/pinephone-fingerprint/./pia.py", line 57, in call
    return self.parse(command, response)
  File "/home/mobian/src/pinephone-fingerprint/./pia.py", line 39, in parse
    if (response[:3] != self.HEADER): raise ValueError("Incorrect header", response[:3])
ValueError: ('Incorrect header', bytearray(b'\x00\xff\xff'))
```

note, i've modified the exception output so that it only shows the 3 bytes which are compared.

```
@@ -36,7 +36,7 @@ class PIA(periphery.I2C):
                return bytearray(response.data)
 
        def parse(self, command, response):
-               if (response[:3] != self.HEADER): raise ValueError("Incorrect header", response)
+               if (response[:3] != self.HEADER): raise ValueError("Incorrect header", response[:3])
```

some additional troubleshooting bits:

```
# i2cdetect -l
i2c-0	i2c       	mv64xxx_i2c adapter             	I2C adapter
i2c-1	i2c       	mv64xxx_i2c adapter             	I2C adapter
i2c-2	i2c       	mv64xxx_i2c adapter             	I2C adapter
i2c-3	i2c       	i2c-csi                         	I2C adapter
i2c-4	i2c       	DesignWare HDMI                 	I2C adapter
i2c-5	i2c       	i2c-1-mux (chan_id 0)           	I2C adapter

# i2cdetect -F 2
Functionalities implemented by /dev/i2c-2:
I2C                              yes
SMBus Quick Command              yes
SMBus Send Byte                  yes
SMBus Receive Byte               yes
SMBus Write Byte                 yes
SMBus Read Byte                  yes
SMBus Write Word                 yes
SMBus Read Word                  yes
SMBus Process Call               yes
SMBus Block Write                yes
SMBus Block Read                 no
SMBus Block Process Call         no
SMBus PEC                        yes
I2C Block Write                  yes
I2C Block Read                   yes

# i2cdetect -y 2
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- 28 -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
```

**Comment by egormanga** [comment]
That's exactly what we are addressing on a personal email conversation with the project author.

By the way, thank you for the exception patch — I'll apply that.

**Comment by khimaros** [comment]
@egormanga -- thank you for the reply! let me know if i can help in any way.

btw, it looks like `i2ctransfer` might be a helpful tool for rapid testing.

have you found a way to reset the i2c device when it is stuck without removing back panel and reattaching?

**Comment by egormanga** [comment]
No I did not. There's no such feature implemented on the hardware nor firmware side.

As per [datasheet](https://files.pine64.org/doc/PinePhone/Schematic_fingerprint%20driver%20board%20V3_2021-01-24.pdf), attiny's reset pin is not connected anywhere. That in particular is not a problem, because there's no place to connect it anyway.

What the problem is — that the sensor's reset line isn't connected too. And that one is not quite easy to fix: there's no such pin on the sensor header. A proper resetting of the sensor must be done via the power line, and that involves a lot of hardware changes, not even possible to be custom-modded.

But, as I guess, the sensor is stateless, so there should be no such situation in which a reset would be needed in the first place.

For the attiny it should be relatively trivial to implement a software `reboot` command if would be needed. Also, it would be great to have a firmware update via I2C feature, which is something not being addressed currently at all.

**Comment by khimaros** [comment]
indeed, the firmware seems quite simple. it's a bit interesting seeing the `!!!UNTESTED!!!` in https://github.com/zschroeder6212/tiny-i2c-spi/blob/master/src/main.c#L99 :)

it seems like since there is no firmware update mechanism built-in, it may not be possible to update without a hardware mod?

**Comment by egormanga** [comment]
Well, as for updating the firmware, it could be accomplished by disassembling the unit and connecting an SPI programmer onto the exposed ICSP header (I suppose; never seen the schematic to confirm, and there's no pinout silkprinted on the board itself either). In fact, I'm going to fix and/or rewrite the firmware a bit, also including a mechanism to update it without the need of an external programmer (i.e. from the PinePhone directly). For the units already produced though, it will require a single manual flash first.

Regarding the `UNTESTED` thing, I've actually spotted that the code doing the bit masking is completely wrong (see https://github.com/zschroeder6212/tiny-i2c-spi/issues/3#issuecomment-1039214365; also emailed the author with more details). Even though the author insists that this code branch isn't needed for communicating with this specific sensor, I do think that the defaults are not fully compatible with the ones specified in the sensor [datasheet](https://github.com/zschroeder6212/tiny-i2c-spi/issues/2#issuecomment-1029218452) (`cpol`/`cpha`, specifically). This is also confirmed by the fact my code doesn't work (I hope; as otherwise it will be my mistake).

**Comment by khimaros** [comment]
re: flashing the firmware, i wonder if a strategy similar to https://codingfield.com/blog/2021-11/flash-the-lora-pinephone-backplate/ would work for the fingerprint panel as well?

their success speaking with the SPI LoRa device over the same I2C firmware may actually be relevant here: https://codingfield.com/blog/2021-11/a-driver-for-the-pinephone-lora-backplate/

the article mentions:

> for some reason, I couldn’t read all the bytes at once, only the first one would contain valid data. That’s why I implemented the read operation in a loop where each iteration reads one byte.

**Comment by egormanga** [comment]
Well, the current build of the firmware is actually flashed right from the factory. As I said, it may or may not be enough to communicate with the sensor chip.
<br>

> I couldn’t read all the bytes at once, only the first one would contain valid data

That's something new. Although the LoRa module uses a slightly different firmware, I'll try to investigate that more. Thanks.
